# -*- coding: utf-8 -*-
"""checkpoint 4_Amandine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rpQylTAUzC4Eev8TwOyIu8Rzk54Tm8Jy

(English version below)

# FR - Etude de marché sur le vin

Le client, le Domaine des Croix, cherche à **définir le prix** de ses bouteilles de vin **pour le marché américain**. Il a récupéré un jeu de données de 130k bouteilles de vin, avec les cépages, les pays et région de production, les millésimes (c'est-à-dire les années de production), ainsi que des notes ("points") et descriptifs d'oenologues (les spécialistes du vin), et le prix en dollars de toutes ces bouteilles sur le marché américain.

**L'objectif sera de faire une présentation de l'analyse du marché, et du prix que tu conseilles de fixer pour les vins du client.** Le client n'est pas data analyst, mais souhaiterait comprendre la démarche. Il faudra donc s'attacher à expliquer comment les prix ont été fixés, sans rentrer dans un trop grand niveau technique, autrement dit : vulgariser.

Tu trouveras ci-dessous des trames pour te guider dans cette analyse. Effectue tout d'abord la trame commune. Puis, tu peux suivre l'une de ces trames (Machine Learning ou Business Intelligence). **Ne cherche pas à effectuer les deux trames ! Choisir, c'est renoncer. Le client préfère un travail qualitatif plutôt qu'un travail exhaustif.**
Mais tu peux aussi partir dans d'autres directions pour répondre à la problématique du client. Si tu as des bonnes idées à proposer au client, elles sont évidemment les bienvenues. C'est toi le Data Analyst maintenant. 




# Jeux de données
- Dataset des 130k vins : https://github.com/murpi/wilddata/raw/master/wine.zip
- Dataset des 14 vins du Domaine des Croix : https://github.com/murpi/wilddata/raw/master/domaine_des_croix.csv


# Livrables attendus
Le client souhaite une présentation de 10 minutes suivi de 10 minutes de questions. 
La présentation contiendra a minima ces éléments :
- Rappel du contexte et de la problématique
- Analyse exploratoire des données
- Méthodologie, outils et langages utilisés
- Présentation de la partie technique et du code créé pour cette analyse
- Réponse à la question métier : proposition de prix ou de fourchette de prix au client pour être correctement positionné face à la concurrence sur le marché américain

# Common framework: data preparation and exploratory analysis

## FR - Preprocessing
La colonne "title" contient le domaine, le millésime et le cépage ("variety"). Tu dois isoler le millésime (l'année) dans une colonne dédiée.


## Analyse du marché
Le Domaine des Croix souhaiterait une analyse descriptive du marché du vin. Tu vas donc réaliser un ensemble de dataviz, avec l'outil de ton choix (Seaborn, Plotly, Excel, PowerBI, Tableau, etc...). Par exemple : 
- la répartition du nombre de vins par pays
- les pays qui ont les meilleures notes
- les moyennes de notes par cépage
- la répartition par décile
- etc...

Le client souhaiterait un zoom spécifique sur le cépage ("variety") Pinot Noir.


## Descriptions
Quels sont les mots qui ressortent le plus dans les descriptions des vins ? Et spécifiquement pour le pinot noir, est-ce très différent ?  Et pour la province Burgundi en France ?

# Framework: Business Intelligence

## FR - Analyse comparative

L'objectif ici sera de comparer chacun des vins du client par rapport à ses concurrents sur le marché. Par exemple, comparer les tarifs pratiqués pour les vins français, puis de plus en plus précisément, les vins de Bourgogne puisque notre client est en Bourgogne, puis les Pinot Noir bourguignons de la même année.
N'hésite pas à être original dans la présentation et les dataviz utilisées. Utilise toutes les fonctionnalités de Business Intelligence dans un tableau de bord pour aider au mieux le client à se comparer (infobulles, filtres, etc...).

## Proposition de valeur

Avec le tableau de bord que tu lui as fourni, le client a une idée précise de ses concurrents. Fais lui une proposition de prix en fonction de sa volonté de positionnement (par exemple : "si vous souhaitez vous positionner sur le haut de gamme, les 25% les plus chers de vos concurrents sont à ce tarif, nous vous conseillons donc de vous aligner sur ce prix").

## Qualité esthétique du tableau de bord

Essaye de garder un oeil critique et visuel sur ton tableau de bord. La forme compte autant que le fond pour le client qui n'est pas data analyst. Pense donc à "vendre" ton analyse. Par exemple, avec des couleurs s'inspirant du milieu vinicole, des dataviz originales, etc...

# It's up to you now:

# 💾  Import
"""

import pandas as pd
import re
import seaborn as sns
import matplotlib.pyplot as plt
import spacy
from wordcloud import WordCloud
import plotly.express as px

import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

link = "https://github.com/murpi/wilddata/raw/master/wine.zip"
df = pd.read_csv(link)

df.head()

link_deux = "https://raw.githubusercontent.com/murpi/wilddata/master/domaine_des_croix.csv"
df_domaine = pd.read_csv(link_deux)

df_domaine.head()

"""# 🔍  I - Exploration

* df_domaine = df du domaine de la croix
* df = df des vins

## A -  Exploration / états des lieux des deux df
"""

df_domaine.shape

df_domaine.info()

df_domaine.describe()

df.shape

df.info()

df.describe()

"""## B - Exploration par colonnes

### Dataframe général sur le vin : df

#### a - Les pays - Colonne "country"
"""

df['country'].value_counts()

df['country'].describe()

# On recherche les valeurs manquantes

country_nan = df['country'].isna().sum()
country_nan

# On remplace les valeurs manquantes par "inconnu"

df['country'].fillna('inconnu', inplace=True)

# On vérifie : il n'y a plus de valeurs manquantes

df['country'].isna().sum()

# On regarde combien de pays différent il y a.
# On voit que "inconnu" s'est bien rajouté également
df['country'].unique()

# Il y a bien 44 pays différents sur le df
df['country'].nunique()

"""#### b - Designation"""

# On vérifie les valeurs manquantes
df['designation'].isna().sum()

# On remplace les valeurs manquantes
df['designation'].fillna('inconnu', inplace=True)

# On vérifie : il n'y a plus de valeurs manquantes
df['designation'].isna().sum()

df['designation'].value_counts()

"""#### c - Description des vins"""

# On vérifie les valeurs manquantes
df['description'].isna().sum()

"""#### d - Points - Colonne points"""

# On vérifie la répartition des points 
df['points'].value_counts()

# On regarde les stats sur la colonne points
df['points'].describe()

"""* Le max des points est de 100
* Un vin tourne en moyenne à 88 points
"""

# On vérifie les valeurs manquantes
# Il n'y en a pas 
df['points'].isna().sum()

"""#### e - Prix - Colonne price"""

df['price'].describe()

"""* Idée : le vin le plus cher est à 1902 dollars et le moins cher à 2 dollars.
* On tourne autour de 36 dollars la bouteille de vin 
"""

pd.DataFrame(df['price'].value_counts())

"""* Les prix qui ressortent le plus sont 24 et 21 dollars la bouteille"""

# Vérification des valeurs manquantes
# On a 8993 valeurs manquantes pour le prix
df['price'].isna().sum()

# On regarde le pourcentage de valeurs manquantes par rapport au df
pourcent_manquantes = round(df['price'].isnull().sum()*100/len(df['price']))
print("Il y a ", pourcent_manquantes, "% de valeurs manquantes.\
Cela étant peu, elles ne seront pas remplacées")

"""#### f - Province"""

df['province'].value_counts()

df['province'].isna().sum()

df['province'].fillna('inconnu', inplace = True)

df['province'].unique()

df['province'].nunique()

"""#### g - Variété"""

df['variety'].value_counts()

# On vérifie combien de variété différentes il y a
df['variety'].nunique()

""" Il y a 707 variétés de vin"""

df['variety'].unique()

# On vérifie les valeurs manquantes
df['variety'].isna().sum()

# On remplace la valeur manquante par "inconnu"
df['variety'].fillna('inconnu', inplace=True)

# On vérifie, il n'y a plus de valeurs manquantes
df['variety'].isna().sum()

"""#### h - Domaine"""

df['winery'].value_counts()

# On vérifie combien de domaine différents il y a
df['winery'].nunique()

"""Il y a 16756 domaines différents"""

# On vérifie si il y a des valeurs manquantes
# Pas de valeurs manquantes
df['winery'].isna().sum()

"""#### i - Région 1"""

df['region_1'].value_counts()

# On vérifie les valeurs manquantes
df['region_1'].isna().sum()

# On regarde le pourcentage de valeurs manquantes par rapport au df
prcent_manquante = round(df['region_1'].isnull().sum()*100/len(df['region_1']))
print("Il y a ", prcent_manquante, "% de valeurs manquantes")

"""* Il y a trop de valeurs manquantes dans cette colonne, on ne la garde pas.

#### j - Région 2
"""

df['region_2'].value_counts()

# On vérifie les valeurs manquantes
df['region_2'].isna().sum()

# On regarde le pourcentage de valeurs manquantes par rapport au df
prct_manquante = round(df['region_2'].isnull().sum()*100/len(df['region_2']))
print("Il y a ", prct_manquante, "% de valeurs manquantes")

"""* Il y a trop de valeurs manquantes dans cette colonne, on ne la garde pas.

#### k - Taster name
"""

df['taster_name'].value_counts()

# On regarde les valeurs manquantes
df['taster_name'].isna().sum()

# On regarde le pourcentage de valeurs manquantes
pourcent_manquantes = round(df['taster_name'].isnull().sum()*100/len(df['taster_name']))
print("Il y a ", pourcent_manquantes, "% de valeurs manquantes")

"""* Il y a beaucoup de valeurs manquantes, mais la colonne n'étant pas du numérique on va remplacer les valeurs manquantes par "inconnu"



"""

# On remplace les valeurs manquantes
df['taster_name'].fillna('inconnu', inplace=True)

# On vérifie si inconnu s'est bien substitué
df['taster_name'].unique()

"""#### l - twitter"""

df['taster_twitter_handle'].value_counts()

df['taster_twitter_handle'].isna().sum()

# On regarde le pourcentage de valeurs manquantes
pourcent_manquantes = round(df['taster_twitter_handle'].isnull().sum()\
                            * 100 / len(df['taster_twitter_handle']))
print("Il y a ", pourcent_manquantes, "% de valeurs manquantes")

"""* Il y a beaucoup de valeurs manquantes, mais la colonne n'étant pas du numérique on va remplacer les valeurs manquantes par "inconnu"
"""

# On remplace les valeurs manquantes
df['taster_twitter_handle'].fillna('inconnu', inplace=True)

# On vérifie si inconnu s'est bien substitué
df['taster_twitter_handle'].unique()

"""### Dataframe du domaine : df_domaine

#### a - Les pays
"""

# On vérifie même si logiquement il n'y a qu'un seul pays : la France
df_domaine['country'].value_counts()

# On vérifie les valeurs manquantes
df_domaine['country'].isna().sum()

"""* Pas de valeurs manquantes

#### b - Designation
"""

df_domaine['designation'].value_counts()

# On regarde les différentes designation
df_domaine['designation'].unique()

# On regarde le nombres de designation
df_domaine['designation'].nunique()

# On vérifie les valeurs manquantes
df_domaine['designation'].isna().sum()

# on remplace les 5 valeurs manquantes par "inconnu"
df_domaine['designation'].fillna('inconnu', inplace=True)

# On vérifie que les valeurs manquantes n'y sont plus
df_domaine['designation'].isna().sum()

# On voit que inconnu s'est bien substitué
df_domaine['designation'].unique()

"""#### c - Description des vins"""

# On vérifie les valeurs manquantes
df_domaine['description'].isna().sum()

"""#### d - Points"""

# On vérifie la répartition des points 
df_domaine['points'].value_counts()

# On regarde les stats sur la colonne points
df_domaine['points'].describe()

"""* Les points les plus haut ici sont de 95.
* Un vin tourne en moyenne à 93 points.
"""

# On regarde les valeurs manquantes
df_domaine['points'].isna().sum()

"""* Il n'y a pas de valeurs manquantes pour les points

#### e - Prix
"""

df_domaine['price'].describe()

# On vérifie les valeurs manquantes
df_domaine['price'].isna().sum()

"""* Il n'y a pas de prix c'est normal.

#### f - Province
"""

# On regarde si il y a différentes provinces quand même
df_domaine['province'].value_counts()

df_domaine['province'].unique()

"""* On a qu'une seule province, c'est normal"""

# On vérifie les valeurs manquantes
df_domaine['province'].isna().sum()

"""* il n'y a pas de valeurs manquantes

#### g - Variété
"""

df_domaine['variety'].value_counts()

# On vérifie combien de variété différentes il y a
df_domaine['variety'].nunique()

"""* Il n'y a que 2 variétés"""

# On vérifie les valeurs manquantes
df_domaine['variety'].isna().sum()

"""* il n'y a pas de valeurs manquantes

#### h - Domaine
"""

# On vérifie qu'il n'y a bien qu'un seul domaine
df_domaine['winery'].value_counts()

# On vérifie les valeurs manquantes
df_domaine['winery'].isna().sum()

"""* Pas de valeurs manquantes

#### i - Région 1
"""

df_domaine['region_1'].value_counts()

# On vérifie les différentes régions
df_domaine['region_1'].unique()

df_domaine['region_1'].nunique()

# On vérifie les valeurs manquantes
df_domaine['region_1'].isna().sum()

"""* Pas de valeurs manquantes

#### j - Région 2
"""

df_domaine['region_2'].value_counts()

# On vérifie les valeurs manquantes
df_domaine['region_2'].isna().sum()

# On regarde le pourcentage de valeurs manquantes par rapport au df
pourcent_manquantes = round(df_domaine['region_2'].isnull().sum()\
                            * 100 / len(df_domaine['region_2']))
print("Il y a ", pourcent_manquantes, "% de valeurs manquantes")

"""* Trop de valeurs manquantes, on ne les remplace pas et on ne gardera pas la colonne

#### k - Taster name
"""

df_domaine['taster_name'].value_counts()

# On vérifie qu'il n'y a bien qu'un taster name
df_domaine['taster_name'].unique()

df_domaine['taster_name'].nunique()

# On regarde les valeurs manquantes
df_domaine['taster_name'].isna().sum()

"""* Pas de valeurs manquantes

#### l - Twitter
"""

df_domaine['taster_twitter_handle'].value_counts()

# On vérifie qu'il n'y a bien qu'un taster name
df_domaine['taster_twitter_handle'].unique()

df_domaine['taster_twitter_handle'].nunique()

df_domaine['taster_twitter_handle'].isna().sum()

"""* Pas de valeurs manquantes

# 🗓 II - Création d'une colonne pour les dates

* Analyse : les deux df ne comportent pas de colonne concernant l'année du vin. D'un point de vue métier l'année d'un vin est importante. Elle peut jouer sur sa notation mais aussi et surtout sur le prix de celui-ci.
"""

# On test extract pour garder que la date
test = pd.Series('Domaine des Croix 2016 Corton Grèves')
test.str.extract(r'(\d{4})')

# C'est ok donc on l'applique à tout le df_domaine et on crée une colonne
df_domaine['millesime'] = df_domaine['title'].str.extract(r'(\d{4})')

df_domaine.head(1)

df['millesime'] = df['title'].str.extract(r'(\d{4})')

df.head(1)

"""# 🧮 III - Création de df supplémentaires

* Pour faire des analyses précises et des visualisations plus simples à réaliser on crée des df sur des points précis de l'analyse à fournir au client.
* Nécessaire pour la description des mots NLP

## A - Création d'un df de vin français
"""

# on garde que le pays france dans la colonne country
df_vin_france = df[df['country'] == 'France']
df_vin_france

# On vérifie qu'on a bien que des vins français
df_vin_france['country'].value_counts()

df_vin_france['country'].unique()

"""## B - Création d'un df de vin de Bourgogne

* On en va garder que les vins de bourgogne sur "df" le dataframe global des vins. Le df_domaine ne contient déjà que des vins de bourgogne
"""

df_vin_bourgogne = df[df['province'] == 'Burgundy']
df_vin_bourgogne

# On vérifie qu'on a bien que des vins de bourgogne
df_vin_bourgogne['province'].value_counts()

df_vin_bourgogne['province'].unique()

"""## C - Création d'un df de Pinot noir

## 1 - Création d'un df de Pinot noir sur le df global

### a - On vérifie les pinot noirs différents et on crée un df de pinot noir
"""

df['variety'].unique().tolist()

# Pour contenir tout les pinot noir y compris les pinot noir syrah etc 
df_pinotnoir = df[df['variety'].str.contains('Pinot Noir')]
df_pinotnoir

"""### b - Vérif sur ce nouveau df pinotnoir"""

df_pinotnoir.shape

df_pinotnoir.info()

df_pinotnoir.describe()

"""## 2 -  Création d'un df de pinot noir sur le df_domaine

### a - Création par rapport à la variété Pinot noir
"""

df_domaine['variety'].unique().tolist()

df_pinotnoir_domaine = df_domaine[df_domaine['variety'] == 'Pinot Noir']
df_pinotnoir_domaine

"""### b - Verif sur ce nouveau df_pinotnoir_domaine"""

df_pinotnoir_domaine.shape

df_pinotnoir_domaine.info()

df_pinotnoir_domaine.describe()

"""# 🧐 IV - Analyse

* On renomme le dataframe df par df_vins pour plus de clareté
"""

df_vins = df

"""### Correlation des prix

* On regarde la correlation entre le prix et les points avec une heatmap puis avec un pairplot
"""

vins_corr = df_vins.corr()
sns.heatmap(vins_corr,
            center=0,
            cmap="vlag",
            annot=True
            )

plt.title("Correlation prix/points vins")
plt.show()

"""* On observe une correlation de 0.47, la correlation est positive mais elle n'est pas très elevée. """

domaine_corr = df_domaine.corr()
sns.heatmap(domaine_corr,
            center=0,
            cmap="vlag",
            annot=True
            )

plt.title("Correlation prix/points domaine")
plt.show()

"""* Ici c'est normal car les prix ne sont pas fixés"""

sns.pairplot(df_vins)

fig = px.scatter_matrix(df_vins,
    dimensions=["points", "price"])

fig.show()

sns.pairplot(df_vins,
             hue='country')
plt.show()

"""* Ici on regarde en plus si le pays de provenance pour cette correlation entre les prix et les points attribués. 
* On observe que les vins provenant de France, du portugal, d'espagne, des états-unis et d'italie sont majoritairement présent.
"""

sns.pairplot(df_vins,
             hue='variety'
             )
plt.show()

plt.boxplot(df_vins["points"])
plt.show()

df_domaine[["points"]].boxplot()

"""### Foire à la Dataviz (idées de graphs)

#### Analyse des points
"""

ax, fig = plt.subplots(figsize=(16, 8))
sns.boxplot(x='country',
            y='points',
            data=df_vins,
            color='purple')
plt.title("Boxplot pays / notes")
plt.xlabel("Pays", size=11)
plt.ylabel("Points", size=11) 

plt.show()

sns.boxplot(x=df_vins['points'],
            color = 'purple')
plt.title("Boxplot des notes")
plt.show()

sns.boxplot(x=df_domaine['points'],
            color='purple')
plt.title("Boxplot des notes/domaine")
plt.show()

sns.boxplot(x=df_vin_bourgogne['points'],
            color='purple')
plt.title("Boxplot des notes/bourgogne")
plt.show()

sns.countplot(x = 'points',
              data=df_vin_bourgogne,
              color='lightblue')
plt.title("Répartition des points sur les vins de Bourgogne")
plt.xlabel("Points", size=11)  
    
plt.show()

sns.countplot(x = 'points',
              data=df_domaine,
              color='royalblue')
plt.title("Répartition des points sur les vins du domaine")
plt.xlabel("Points", size = 11)
    
plt.show()

sns.countplot(x = 'points',
              data=df_vin_france,
              color='blue'
              )
plt.title("Répartition des points sur les vins de France")
plt.xlabel("Points", size=11)

    
plt.show()

sns.countplot(x = 'points',
              data=df_vins,
              color='purple'
              )
plt.title("Répartition des points sur les vins")
plt.xlabel("Points", size=11)

    
plt.show()

plt.figure(figsize=(20,10))
sns.countplot(x = 'country',
              data=df_vins,
              order=df_vins['country'].value_counts().index,
              color='lightblue')
plt.title("Répartition nombres de vin par pays")
plt.xlabel("Points", size=11)  

    
plt.show()

"""#### Analyse des prix"""

#plt.figure(figsize=(12,7))
sns.boxplot(x=df_vins['price'],
            color='purple')
plt.title("Boxplot des prix")
plt.show()

#plt.figure(figsize=(12,7))
sns.boxplot(x=df_vin_bourgogne['price'],
            color='purple')
plt.title("Boxplot des prix/bourgogne")
plt.show()

ax, fig = plt.subplots(figsize = (16, 8))
sns.countplot(x = 'price',
              data=df_vins,
              color='lightblue')
plt.title("Répartition des prix sur les vins de Bourgogne") 
plt.xticks(rotation = 90)
    
plt.show()

"""#### Analyse pour le pinot noir"""

#plt.figure(figsize=(12,7))
sns.boxplot(x=df_pinotnoir['points'],
            color='purple')
plt.title("Boxplot des notes/pinot")
plt.show()

#plt.figure(figsize=(12,7))
sns.boxplot(x=df_pinotnoir['price'],
            color='purple')
plt.title("Boxplot des prix/pinot")
plt.show()

sns.countplot(x = 'points',
              data=df_pinotnoir,
              color='royalblue')
plt.title("Répartition des points sur les vins Pinot Noir")
plt.xlabel("Points", size=11)  
    
plt.show()

fig = plt.subplots(figsize = (16, 8))
sns.countplot(x = 'province',
              data = df_pinotnoir,
              color = 'blue')
plt.title("Répartition des points sur les vins Pinot Noir")
plt.xlabel("Points", size = 11)  

    
plt.show()

"""#### Analyse sur les différentes colonnes

##### Année - Millesime
"""

df_vins['millesime'].value_counts()

fig = plt.subplots(figsize = (17, 8))
sns.countplot(x = 'millesime',
              data=df_vins,
              color='purple',
              order = df_vins['millesime'].value_counts().index
              )

plt.title("Répartition des vins selon le millesime")
plt.xlabel("annee", size = 11)


plt.show()

df_vin_france['millesime'].value_counts()

sns.countplot(x = 'millesime',
              data=df_vin_france,
              color='purple',
              order=df_vin_france['millesime'].value_counts().index)

plt.title("Répartition des vins de France selon le millesime")
plt.xlabel("annee", size=11)


plt.show()

df_vin_bourgogne['millesime'].value_counts()

sns.countplot(x = 'millesime', data=df_vin_bourgogne,
              color='purple',
              order=df_vin_bourgogne['millesime'].value_counts().index)

plt.title("Répartition des vins de Bourgogne selon le millesime")
plt.xlabel("annee", size=11)


plt.show()

df_pinotnoir['millesime'].value_counts()

sns.countplot(x = 'millesime', data=df_pinotnoir,
              color='purple',
              order=df_pinotnoir['millesime'].value_counts().index)

plt.title("Répartition des vins pinot noir selon le millesime")
plt.xlabel("annee", size=11)


plt.show()

df_pinotnoir_domaine['millesime'].value_counts()

sns.countplot(x = 'millesime',
              data=df_pinotnoir_domaine,
              color='blue',
              order=df_pinotnoir_domaine['millesime'].value_counts().index
              )

plt.title("Répartition vins du domaine par millesime")
plt.xlabel("annee", size = 11)


plt.show()

"""* **Reprise et poursuite de l'analyse sur Tableau**

# 💬 V - Description mots

## Préparation générale
"""

# Ajout des stopwords 
stopwordsenglish = list(nltk.corpus.stopwords.words("english"))

liste_mots_vin = ["wine", "drink"]

stopwordsenglish.extend(liste_mots_vin)

# Création d'une fonction de clean de la colonne

def func_clean2(phrase):

    sentence_upt = ""
    tokens_clean = []

    sent_tokens = nltk.word_tokenize(phrase.lower())
    for words in sent_tokens:
        if words not in stopwordsenglish and not words.isnumeric():
            tokens_clean.append(words)
    f_sentence = ' '.join(tokens_clean)
    f_sentence = re.sub(r'[^\w\s]', '', f_sentence)

    return f_sentence

"""## Application au df_bourgogne"""

# Application de la fonction à la colonne description

df_vin_bourgogne['col_clean'] = df_vin_bourgogne['description'].apply(func_clean2)

df_vin_bourgogne['col_clean'].map(word_tokenize)

# préparation du texte propre

colonne_propre = " ".join([str(word) for word in df_vin_bourgogne['col_clean']])
colonne_propre

"""### ☁️ Wordcloud Bourgogne """

wordcloud = WordCloud(width=480,
                      height=480,
                      max_font_size=200,
                      min_font_size=10,
                      background_color="white"
                      )

token_mots_deux = nltk.word_tokenize(colonne_propre)
mot_fdist_deux = nltk.FreqDist(token_mots_deux)
wordcloud.generate_from_frequencies(mot_fdist_deux)

plt.figure(figsize=(20, 10))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.margins(x=0, y=0)
plt.show()

"""## Application au df de vin français"""

# Application de la fonction à la colonne description

df_vin_france['col_clean'] = df_vin_france['description'].apply(func_clean2)

# préparation du texte propre

colonne_propre_vinfr = " ".join([str(word) for word in df_vin_france['col_clean']])
colonne_propre_vinfr

"""### ☁️ Wordcloud vin français"""

wordcloud_vinfr = WordCloud(width=480,
                      height=480,
                      max_font_size=200,
                      min_font_size=10,
                      background_color="white"
                      )

token_mots_vinfr = nltk.word_tokenize(colonne_propre_vinfr)
mot_fdist_vinfr = nltk.FreqDist(token_mots_vinfr)
wordcloud_vinfr.generate_from_frequencies(mot_fdist_vinfr)

plt.figure(figsize=(20, 10))
plt.imshow(wordcloud_vinfr, interpolation="bilinear")
plt.axis("off")
plt.margins(x=0, y=0)
plt.show()

"""## Application au df pinotnoir"""

# Application de la fonction à la colonne description

df_pinotnoir['col_clean'] = df_pinotnoir['description'].apply(func_clean2)

# préparation du texte propre

colonne_propre_pinot = " ".join([str(word) for word in df_pinotnoir['col_clean']])
colonne_propre_pinot

"""### ☁️ Wordcloud pinot noir"""

wordcloud_pinot = WordCloud(width=480,
                      height=480,
                      max_font_size=200,
                      min_font_size=10,
                      background_color="white"
                      )

token_mots_pinot = nltk.word_tokenize(colonne_propre_pinot)
mot_fdist_pinot = nltk.FreqDist(token_mots_pinot)
wordcloud_pinot.generate_from_frequencies(mot_fdist_pinot)

plt.figure(figsize=(20, 10))
plt.imshow(wordcloud_pinot, interpolation="bilinear")
plt.axis("off")
plt.margins(x=0, y=0)
plt.show()

"""## Application au df du domaine"""

# Application de la fonction à la colonne description

df_domaine['col_clean'] = df_domaine['description'].apply(func_clean2)

# préparation du texte propre
colonne_propre_domaine = " ".join([str(word) for word in df_domaine['col_clean']])
colonne_propre_domaine

"""### ☁️ Wordlcoud df domaine"""

wordcloud_domaine = WordCloud(width=480,
                      height=480,
                      max_font_size=200,
                      min_font_size=10,
                      background_color="white"
                      )

token_mots_domaine = nltk.word_tokenize(colonne_propre_domaine)
mot_fdist_domaine = nltk.FreqDist(token_mots_domaine)
wordcloud_domaine.generate_from_frequencies(mot_fdist_domaine)

plt.figure(figsize=(20, 10))
plt.imshow(wordcloud_domaine, interpolation="bilinear")
plt.axis("off")
plt.margins(x=0, y=0)
plt.show()

"""## Application au df de vin général"""

df_vins['col_clean'] = df_vins['description'].apply(func_clean2)

# préparation du texte propre
colonne_propre_vins = " ".join([str(word) for word in df_domaine['col_clean']])
colonne_propre_vins

"""### ☁️ Wordcloud df global"""

wordcloud_vins = WordCloud(width=480,
                      height=480,
                      max_font_size=200,
                      min_font_size=10,
                      background_color="white"
                      )

token_mots_vins = nltk.word_tokenize(colonne_propre_vins)
mot_fdist_vins = nltk.FreqDist(token_mots_vins)
wordcloud_vins.generate_from_frequencies(mot_fdist_vins)

plt.figure(figsize=(20, 10))
plt.imshow(wordcloud_vins, interpolation="bilinear")
plt.axis("off")
plt.margins(x=0, y=0)
plt.show()

"""# Export des df pour Tableau"""

from google.colab import files

df_vins.to_csv('df_vins.csv', encoding = 'utf-8-sig')

files.download('df_vins.csv')

df_domaine.to_csv('df_domaine.csv', encoding = 'utf-8-sig')

files.download('df_domaine.csv')